### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/funcom/data/standard/tdats.tok'

### ISSUE THREAD

**Issue by HaiboWang1992** [mcmillco/funcom#3]
Hi,
I follow the instructions in the README.md, The dependencies in step 0 are well installed, the datasets in step 1 are downloaded from https://s3.us-east-2.amazonaws.com/icse2018/index.html and directories are created follow the step 1. When it comes to step 2, i run the command "time python3 train.py --model-type=attendgru --gpu=0", i get the following error:
![image](https://user-images.githubusercontent.com/71980103/109069043-96d58d00-76e8-11eb-9d38-9758a93ecdea.png)

as showed in the screenshoot, i look through the path '/scratch/funcom/data/standard/', there is no file named 'tdats.tok'.

I look the train.py too, around line 104,  it opens four files, but only the smls.tok and coms.tok are in the path '/scratch/funcom/data/standard/', the other two files tdats.tok and sdats.tok are not in the path at all.
![image](https://user-images.githubusercontent.com/71980103/109069625-617d6f00-76e9-11eb-8d70-c924d737c1ee.png)

Do you have any ideas what should i do to resolve the problem?
I would be so appriciate if you could give me some suggestions.

**Comment by mcmillco** [comment]
I think you may be mixing and matching code and datasets.  On the one hand, there is a reproducibility dataset from our ICSE'19 paper.  It seems you have that one.  It has some old settings in it, like using "dats.tok" instead of the updated "tdats.tok".  You should be able to make it work just by renaming "dats.tok" to "tdats.tok" and changing a few directory settings (via the --data flag to train.py).  I notice that you are looking for /scratch/funcom/data/standard, which is the default data directory.  But your data seems to be in ~/wanghaibo/deep/otherexample/func/funcom/scratch/funcom/data/standard.  You need to tell train.py where to find the data in the relative path via the --data flag.

Another solution would be to use our new dataset via http://leclair.tech/data/funcom/  Look for the tokenized dataset.  It should have the latest tdats.tok etc. files.  You will still need to set the --data flag correctly, though.

**Comment by mcmillco** [comment]
You may also be interested in:
https://github.com/acleclair/ICPC2020_GNN

This repository is much newer and shows an implementation and data for a GNN baseline from our ICPC'20 paper.  The dataset associated with that paper may be more what you are looking for (since it is all entirely processed etc. using the newer scripts).

**Comment by mcmillco** [comment]
Just to make everything 100% clear, I pushed a small change to train.py and predict.py that makes it work without changes for the ICSE reproducibility package (if that is what you are trying to do).  Just be sure to set the data directory with --data (and you may also need to change it in myutils.py, depending on what you are trying to do, you can just try it and see if you get any complaints, if you do check myutils.py).

If you are not interested in reproducing the older paper per se, and just want to start trying out code summarization tools, you may want to jump over to these newer repos:
https://github.com/acleclair/ICPC2020_GNN
https://github.com/Attn-to-FC/Attn-to-FC

**Comment by NoWarnNoError** [comment]
> Hi,
> I follow the instructions in the README.md, The dependencies in step 0 are well installed, the datasets in step 1 are downloaded from https://s3.us-east-2.amazonaws.com/icse2018/index.html and directories are created follow the step 1. When it comes to step 2, i run the command "time python3 train.py --model-type=attendgru --gpu=0", i get the following error:
> ![image](https://user-images.githubusercontent.com/71980103/109069043-96d58d00-76e8-11eb-9d38-9758a93ecdea.png)
> 
> as showed in the screenshoot, i look through the path '/scratch/funcom/data/standard/', there is no file named 'tdats.tok'.
> 
> I look the train.py too, around line 104, it opens four files, but only the smls.tok and coms.tok are in the path '/scratch/funcom/data/standard/', the other two files tdats.tok and sdats.tok are not in the path at all.
> ![image](https://user-images.githubusercontent.com/71980103/109069625-617d6f00-76e9-11eb-8d70-c924d737c1ee.png)
> 
> Do you have any ideas what should i do to resolve the problem?
> I would be so appriciate if you could give me some suggestions.

Hello,
My question is similar to another participant's question, I download the newest dataset from http://leclair.tech/data/funcom/, and I follow the readme split the tokenizer dataset, but how can I get .tok and .plk files as shown in the picture
![屏幕截图 2021-04-06 203844](https://user-images.githubusercontent.com/47051516/113712065-41919000-9718-11eb-9a2a-6968f514fa62.jpg) 
And what is the differences between tdatstok, comstok, smltok and seqdata?
I would be so appreciative if you could give me some suggestions.

**Comment by acleclair** [comment]
I have updated the Reproducibility with an additional link and to be more clear.

You can download the .tok files, fully processed/vectorized dataset, and trained models [HERE](https://icse2018.s3.us-east-2.amazonaws.com/funcom.tar.gz)

The dataset at [http://leclair.tech/data/funcom](http://leclair.tech/data/funcom) is the data before we vectorized it and trained the tokenizers.
